
name: Docker Image CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        perl:
          - 5.22
          - 5.24
          - 5.26
          - 5.28
          - 5.30
          - 5.32

    env:
      DOCKER_USER: ${{ secrets.DOCKER_USER }}
      DOCKER_REPO: ${{ secrets.DOCKER_USER }}/test-images
      IMAGE_TAG: perl-${{ matrix.perl }}

    steps:
      - uses: actions/checkout@v2

      - name: Docker login
        env:
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: docker login -u $DOCKER_USER  -p $DOCKER_PASSWORD

      - name: Build the Docker image
        run: (echo VERSION=${{ matrix.perl }}; echo "cat << EOF"; cat Dockerfile.template; echo "EOF" ) | bash | docker build --tag $DOCKER_REPO:$IMAGE_TAG -

      - name: Push to docker hub
        run: docker push $DOCKER_REPO:$IMAGE_TAG
